/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./app/**/*.{html,js,jsx}",
    "./components/**/*.{html,js,jsx}",
    "./sections/**/*.{html,js,jsx}",
    "./styles/**/*.{js,jsx}",
  ],
  mode: "jit",
  theme: {
    extend: {
      colors: {
        "primary-black": "#1A232E",
        "secondary-white": "#c7c7c7",
        "color-white": "var(--color-white)",
        "color-white30": "var(--color-white30)",
        "color-black": "var(--color-black)",
        "color-green300": "var(--color-green300)",
        "color-green400": "var(--color-green400)",
        "color-green500": "var(--color-green500)",
        "color-green600": "var(--color-green600)",
        "color-green700": "var(--color-green700)",
        "color-green800": "var(--color-green800)",
        "color-gradient": "var(--color-gradient)",
        "color-primary": "var(--color-primary)",
        "color-beige": "var(--color-beige)",
        "color-text-primary": "var(--color-text-primary)",
        "color-text-secondary": "var(--color-text-secondary)",
        "color-primary-accent": "var(--color-primary-accent)",
        "color-opaque": "var(--color-opaque)",
        _fill: "var(--_fill)",
      },
      padding: {
        paddin: "var(--paddin)",
        "spacing-l": "var(--spacing-l)",
        "spacing-m": "var(--spacing-m)",
        "spacing-s": "var(--spacing-s)",
        "spacing-xs": "var(--spacing-xs)",
        "spacing-xl": "var(--spacing-xl)",
        "spacing-xxl": "var(--spacing-xxl)",
      },
      transitionTimingFunction: {
        "out-flex": "cubic-bezier(0.05, 0.6, 0.4, 0.9)",
      },
      fontSize: {
        "font-body": "var(--font-body)",
        "font-h2-display": "var(--font-h2-display)",
        "font-h1": "var(--font-h1)",
        "font-h2": "var(--font-h2)",
        "font-h3": "var(--font-h3)",
        "font-h4": "var(--font-h4)",
        "font-h5": "var(--font-h5)",
        "font-h6": "var(--font-h6)",
        "font-link": "var(--font-link)",
      },
      fontFamily: {
        acorn: ["acorn"],
        titleFont: "var(--titleFont)",
        bodyFont: "var(--bodyFont)",
        ampFont: "var(--ampFont)",
        systemFont: "var(--systemFont)",
      },
      margin: {
        "spacing-xxs": "var(--spacing-xxs)",
      },
    },
  },
  plugins: [],
};
